---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: sno-demo-03
  namespace: sno-demo-03
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: fr-lab
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterDeploymentRef:
    name: sno-demo-03
  # holdInstallation: true
  provisionRequirements:
    workerAgents: 0
    controlPlaneAgents: 1
  imageSetRef:
    name: 'img4.11.22-x86-64-appsub'
  # manifestConfigMapRef:
  #   name : installation-extra-manifests
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.30.0.0/16
    userManagedNetworking: true
  sshPublicKey: >-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyp36ZsMmA0+mG07FlBmv8c0QRxjau/dE6yuGosILypG+/SLjYzN9CO1HwZrINsUkgl+CPjG0/asQZ4mWeDLHIWNEzrK10Cj4vEmGkL5ndgFILQlckWlQo5w7+ny6JO0LH6SxrMxtQ2w73pPtacXlClt6P5txXKTqzk2EzAMQu1LigtWBf6TkW0A2PC3Fu6F8Lw9ECRVd4AZHXdcWWUC04dSTtCS72HDqie+zs8JYlJn39VPOYstAuBb7XM9QsJsEJikVtoVNoL755QktSuXRJ7qXE0OIOY2yeXkRWEasBs9Z2Wo+PoU1m+9CdojZhKqqQxEOZWoufg+KgmS9wsIx7350/a7RI81azKrvpP8jllsRnO3V/SFOJZiXFNltYsGxK7JYBhiKBq2AED37nwyz03O5GA1/AgAlWDJ7O+RSKOQ3FaATEBTU2fXdUAUzCdOuuFaD5tmE/Ewhky3bdd23P4uTsOvQ0RuQGRjvdEXWigepyFcTyswNoUMGWWMZ225c= phuet@phuet-mac
