apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-gitops-clusters-demo
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/clustership/acm-gitops-clusters-demo
      revision: main
      directories:
      - path: clusters/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/clustership/acm-gitops-clusters-demo
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
